# Generated by Django 3.2.17 on 2023-05-11 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at_time', models.DateTimeField()),
                ('lead_passenger_contact_email', models.CharField(max_length=30)),
                ('lead_passenger_contact_number', models.CharField(max_length=30)),
                ('total_booking_cost', models.FloatField()),
                ('payment_confirmed', models.BooleanField()),
                ('transcation_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight_Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_ID', models.IntegerField()),
                ('flight_ticket_cost', models.FloatField()),
                ('departure_location_ID', models.IntegerField()),
                ('arrival_location_ID', models.IntegerField()),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('num_available_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ID', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('nationality_country_ID', models.IntegerField()),
                ('passport_num', models.CharField(max_length=30)),
                ('seat_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat_Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_name', models.CharField(max_length=30)),
                ('available', models.BooleanField()),
                ('flight_ID', models.IntegerField()),
            ],
        ),
    ]
