# Generated by Django 3.2.17 on 2023-05-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_instance',
            name='airline_name',
            field=models.CharField(default='KeeganAirline', max_length=30),
            preserve_default=False,
        ),
    ]
